language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script: pytest
deploy:
  provider: heroku
  app: simplecalculus
  api_key:
    secure: "E++7fjGnKIAShxvLFkvExHGGpcTi1rGw7mBa9NdkkmwRwChuK0xTI/73Pz0GNXPEAjWC0/Vgmcr+3mD7nv+slnRGsTM1bueHGw0GT/96Tr0tNnniwtZb9lrOIDBNegFgwn0Y+FFd7hNRvgOdPCfa1MEwNCexpHV8fal8U7XNiEfh4RAFNGRVsG4fm/lcMA4mz3Ge2wfy0Ptu8pUexPGKMchH9ANohSotbJpvuaaN1t1rSRpnnG68a2XPNnygmkxKW2T9bR7xPkP19c0oOaXR0NTD6VMUQEF5CuTJO73I2IWMaNvpBIwk7628mWQoGS4VBa3RiLnfMHCZxZjGBCrEG2dC5cfHqQL73/R3QNFcRUGZ3f5P8SajLOk5drl7zRGuAuZpq/j8yVW0lp73CBwUvI9+onZMKAQ/CtvOWs0FQak4CBmPQKJxK9d6DegOP2Gupsdn7WCSfWf1+77Rg0gbuYMLZ4SQ/OXYe9acToyoZ9dMp3vIZPhE4l4C3M4KRdwg+QX0WwXx3fZ8eEitVyzacVLu3rs78jGYTkG3uU4Xrcwgo3cLLsOYE+bfkb7i5V9oWt7Sb0nwjUjNmerbjM61WrK0np1vwvbni4FxmDiVKmtM5GVKx4ztlx06BKKUXY0bCt+to1Z2Huh4PE5Q0roPFyJr2fxddl4DLvr9ILFoQ90="
