language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script: pytest
deploy:
  provider: heroku
  app: simplecalculus
  api_key:
    secure: "DeH/+Zwmt5xXTLtI90kXU4pQZDeBjFCSHSzhl6nlVh1YjWCr4g/+2gH2qR4HXvQCOGdcfq3DzjvR+lgUwL/bR7jRCChb6krVOK3l4+IHYt/TO67EmJsKkJAycwKPFos91NZY/lMXaIj0mhV4vo5IWmgnga8Oe04Ym4slhPP2kTN1HZ69+mfwGFXm1q16a7RO4mKBIYbe5r60aDd+P8f54lAJ/mWIhJM/5yYdONJNy5ZZl/DOKFitxIv9vOwkopOwyEklK6YDn2HydpQT9QYycBlOkrxicEgtuaf9pRHlo4GJNEWBG+VOo2+zA4d93MqKijhjdRcnf9Ft6RGVB/yuJeRjb0qOZoVnQldhA0T3T9rdJwVHDSY9M31SuZvHk1CcTV/exF+fHoCodKtj0NsqGbXsmBJhAuBsT9vQBnTpGN8Pu4wmxw7SIu3UGzrzLAPsE5wCDKd1ifJMYFr3/gvFbosA+zbr+1gkgtPdeYCx93450VdjH2AAyTKezLXVeYZYrWUIPyIsR/uLDX7MXRrCSHYAAUjCVLvfwxZflWx1v1wcy7ySQzEQ2osQ6LFHQ0n70/s9gVBSIXi/m1ktD+9AQcegDYSJERMOtHDSo4W8/vdrjIfTOPILU2un91YwcSTGvrXgHfg0DZogxllb0kC2EfKBmAMqjeEcYkAzeJ7XoX4="
