language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script: pytest
deploy:
  provider: heroku
  app: simplecalculus
  api_key:
    secure: "DmxQu4toOkKIuTO+ix4KqICmrXMLSGV1ah+M1wR1DrHJNpIGOqQ1/4KEcgAJEdMjoSqu+D/0JXeJVzfzvSrGrE36o1R9PFqDAKGPgcSRFSgJSPK82O7EIvrYzoyRYVoW4rRC7s7mC/l0f9gHkKM0Clg/3E2Ems2m5xeWbXvJ754mCWvmnvwwRI3iZ9qeNrTlY+y+ZLnh0EjCqap2Mdf6HQQNNkVKkR5M2X3doQ1sayp7x5xVYAEOz2fuYSdvDMnvSPiMx6F81NV/XGp1bgL96YoWNPADmBseCIjLeMa9LFcXhHY+TLKei3gTNNpzdUr3ksC9eYADgp/TU2oo0PTcTvOBOagKGlKpq5qyfYm0Aj7AsLV8i9n/DPRAlXp14CvQVbmv/NzkQHXfyNrPnWiP/Ay4ytPx3FueEubLPNyUjFKFiRjbBZx8OmJMqGbPC0Ca4soi4iTKpZqnHF9ifdzK3JQbW/IMdzTq4myRz2/dgTo0XwDMaG5Ql+uBA0my4WCdK+FnWtRDlTrWZFSfjeXFE2s0I5488YooDiGgz4zwoUN6Xi/2QcZ1PO3hcyZcNfSv2+u/g17oe6/OTSncAefLN5I9ThBjhJZDkVqgvHOx0lYICvxoczpl5JZJlnbLPe44XJvC6FYQMf8lJPf74ohObqLU/u2tmrLVfB56O1DlOJg="
